package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1



/**
 * Chefdezone generated by hbm2java
 */
public class Chefdezone  implements java.io.Serializable {


     private String codeprepose;
     private Zone zone;
     private Employe employe;

    public Chefdezone() {
    }

    public Chefdezone(Zone zone, Employe employe) {
       this.zone = zone;
       this.employe = employe;
    }
   
    public String getCodeprepose() {
        return this.codeprepose;
    }
    
    public void setCodeprepose(String codeprepose) {
        this.codeprepose = codeprepose;
    }
    public Zone getZone() {
        return this.zone;
    }
    
    public void setZone(Zone zone) {
        this.zone = zone;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }




}


