package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1



/**
 * ChoixId generated by hbm2java
 */
public class ChoixId  implements java.io.Serializable {


     private String codesurveillant;
     private String nomzone;

    public ChoixId() {
    }

    public ChoixId(String codesurveillant, String nomzone) {
       this.codesurveillant = codesurveillant;
       this.nomzone = nomzone;
    }
   
    public String getCodesurveillant() {
        return this.codesurveillant;
    }
    
    public void setCodesurveillant(String codesurveillant) {
        this.codesurveillant = codesurveillant;
    }
    public String getNomzone() {
        return this.nomzone;
    }
    
    public void setNomzone(String nomzone) {
        this.nomzone = nomzone;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChoixId) ) return false;
		 ChoixId castOther = ( ChoixId ) other; 
         
		 return ( (this.getCodesurveillant()==castOther.getCodesurveillant()) || ( this.getCodesurveillant()!=null && castOther.getCodesurveillant()!=null && this.getCodesurveillant().equals(castOther.getCodesurveillant()) ) )
 && ( (this.getNomzone()==castOther.getNomzone()) || ( this.getNomzone()!=null && castOther.getNomzone()!=null && this.getNomzone().equals(castOther.getNomzone()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodesurveillant() == null ? 0 : this.getCodesurveillant().hashCode() );
         result = 37 * result + ( getNomzone() == null ? 0 : this.getNomzone().hashCode() );
         return result;
   }   


}


