package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private String code;
     private BigDecimal nas;
     private String nom;
     private String prenom;
     private Date naissancedate;
     private String nomjeunefille;
     private String adr;
     private String tel;
     private String fonction;
     private String service;
     private Set salaires = new HashSet(0);
     private Chefdezone chefdezone;
     private Surveillant surveillant;

    public Employe() {
    }

	
    public Employe(String code, BigDecimal nas, String nom, String prenom, Date naissancedate, String nomjeunefille, String adr, String tel, String fonction, String service) {
        this.code = code;
        this.nas = nas;
        this.nom = nom;
        this.prenom = prenom;
        this.naissancedate = naissancedate;
        this.nomjeunefille = nomjeunefille;
        this.adr = adr;
        this.tel = tel;
        this.fonction = fonction;
        this.service = service;
    }
    public Employe(String code, BigDecimal nas, String nom, String prenom, Date naissancedate, String nomjeunefille, String adr, String tel, String fonction, String service, Set salaires, Chefdezone chefdezone, Surveillant surveillant) {
       this.code = code;
       this.nas = nas;
       this.nom = nom;
       this.prenom = prenom;
       this.naissancedate = naissancedate;
       this.nomjeunefille = nomjeunefille;
       this.adr = adr;
       this.tel = tel;
       this.fonction = fonction;
       this.service = service;
       this.salaires = salaires;
       this.chefdezone = chefdezone;
       this.surveillant = surveillant;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public BigDecimal getNas() {
        return this.nas;
    }
    
    public void setNas(BigDecimal nas) {
        this.nas = nas;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getNaissancedate() {
        return this.naissancedate;
    }
    
    public void setNaissancedate(Date naissancedate) {
        this.naissancedate = naissancedate;
    }
    public String getNomjeunefille() {
        return this.nomjeunefille;
    }
    
    public void setNomjeunefille(String nomjeunefille) {
        this.nomjeunefille = nomjeunefille;
    }
    public String getAdr() {
        return this.adr;
    }
    
    public void setAdr(String adr) {
        this.adr = adr;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public Set getSalaires() {
        return this.salaires;
    }
    
    public void setSalaires(Set salaires) {
        this.salaires = salaires;
    }
    public Chefdezone getChefdezone() {
        return this.chefdezone;
    }
    
    public void setChefdezone(Chefdezone chefdezone) {
        this.chefdezone = chefdezone;
    }
    public Surveillant getSurveillant() {
        return this.surveillant;
    }
    
    public void setSurveillant(Surveillant surveillant) {
        this.surveillant = surveillant;
    }




}


