package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Espece generated by hbm2java
 */
public class Espece  implements java.io.Serializable {


     private String nom;
     private Lotissement lotissement;
     private BigDecimal nombre;
     private Set individus = new HashSet(0);

    public Espece() {
    }

	
    public Espece(String nom, Lotissement lotissement) {
        this.nom = nom;
        this.lotissement = lotissement;
    }
    public Espece(String nom, Lotissement lotissement, BigDecimal nombre, Set individus) {
       this.nom = nom;
       this.lotissement = lotissement;
       this.nombre = nombre;
       this.individus = individus;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Lotissement getLotissement() {
        return this.lotissement;
    }
    
    public void setLotissement(Lotissement lotissement) {
        this.lotissement = lotissement;
    }
    public BigDecimal getNombre() {
        return this.nombre;
    }
    
    public void setNombre(BigDecimal nombre) {
        this.nombre = nombre;
    }
    public Set getIndividus() {
        return this.individus;
    }
    
    public void setIndividus(Set individus) {
        this.individus = individus;
    }




}


