package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lotissement generated by hbm2java
 */
public class Lotissement  implements java.io.Serializable {


     private LotissementId id;
     private Zone zone;
     private Set especes = new HashSet(0);
     private Set surveillances = new HashSet(0);

    public Lotissement() {
    }

	
    public Lotissement(LotissementId id, Zone zone) {
        this.id = id;
        this.zone = zone;
    }
    public Lotissement(LotissementId id, Zone zone, Set especes, Set surveillances) {
       this.id = id;
       this.zone = zone;
       this.especes = especes;
       this.surveillances = surveillances;
    }
   
    public LotissementId getId() {
        return this.id;
    }
    
    public void setId(LotissementId id) {
        this.id = id;
    }
    public Zone getZone() {
        return this.zone;
    }
    
    public void setZone(Zone zone) {
        this.zone = zone;
    }
    public Set getEspeces() {
        return this.especes;
    }
    
    public void setEspeces(Set especes) {
        this.especes = especes;
    }
    public Set getSurveillances() {
        return this.surveillances;
    }
    
    public void setSurveillances(Set surveillances) {
        this.surveillances = surveillances;
    }




}


