package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LotissementId generated by hbm2java
 */
public class LotissementId  implements java.io.Serializable {


     private BigDecimal numero;
     private String nomzone;

    public LotissementId() {
    }

    public LotissementId(BigDecimal numero, String nomzone) {
       this.numero = numero;
       this.nomzone = nomzone;
    }
   
    public BigDecimal getNumero() {
        return this.numero;
    }
    
    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }
    public String getNomzone() {
        return this.nomzone;
    }
    
    public void setNomzone(String nomzone) {
        this.nomzone = nomzone;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LotissementId) ) return false;
		 LotissementId castOther = ( LotissementId ) other; 
         
		 return ( (this.getNumero()==castOther.getNumero()) || ( this.getNumero()!=null && castOther.getNumero()!=null && this.getNumero().equals(castOther.getNumero()) ) )
 && ( (this.getNomzone()==castOther.getNomzone()) || ( this.getNomzone()!=null && castOther.getNomzone()!=null && this.getNomzone().equals(castOther.getNomzone()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumero() == null ? 0 : this.getNumero().hashCode() );
         result = 37 * result + ( getNomzone() == null ? 0 : this.getNomzone().hashCode() );
         return result;
   }   


}


