package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mesure generated by hbm2java
 */
public class Mesure  implements java.io.Serializable {


     private MesureId id;
     private Individu individu;
     private BigDecimal poids;
     private BigDecimal taille;

    public Mesure() {
    }

    public Mesure(MesureId id, Individu individu, BigDecimal poids, BigDecimal taille) {
       this.id = id;
       this.individu = individu;
       this.poids = poids;
       this.taille = taille;
    }
   
    public MesureId getId() {
        return this.id;
    }
    
    public void setId(MesureId id) {
        this.id = id;
    }
    public Individu getIndividu() {
        return this.individu;
    }
    
    public void setIndividu(Individu individu) {
        this.individu = individu;
    }
    public BigDecimal getPoids() {
        return this.poids;
    }
    
    public void setPoids(BigDecimal poids) {
        this.poids = poids;
    }
    public BigDecimal getTaille() {
        return this.taille;
    }
    
    public void setTaille(BigDecimal taille) {
        this.taille = taille;
    }




}


