package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * MesureId generated by hbm2java
 */
public class MesureId  implements java.io.Serializable {


     private BigDecimal idindividu;
     private Date datemesure;

    public MesureId() {
    }

    public MesureId(BigDecimal idindividu, Date datemesure) {
       this.idindividu = idindividu;
       this.datemesure = datemesure;
    }
   
    public BigDecimal getIdindividu() {
        return this.idindividu;
    }
    
    public void setIdindividu(BigDecimal idindividu) {
        this.idindividu = idindividu;
    }
    public Date getDatemesure() {
        return this.datemesure;
    }
    
    public void setDatemesure(Date datemesure) {
        this.datemesure = datemesure;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MesureId) ) return false;
		 MesureId castOther = ( MesureId ) other; 
         
		 return ( (this.getIdindividu()==castOther.getIdindividu()) || ( this.getIdindividu()!=null && castOther.getIdindividu()!=null && this.getIdindividu().equals(castOther.getIdindividu()) ) )
 && ( (this.getDatemesure()==castOther.getDatemesure()) || ( this.getDatemesure()!=null && castOther.getDatemesure()!=null && this.getDatemesure().equals(castOther.getDatemesure()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdindividu() == null ? 0 : this.getIdindividu().hashCode() );
         result = 37 * result + ( getDatemesure() == null ? 0 : this.getDatemesure().hashCode() );
         return result;
   }   


}


