package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1



/**
 * SalaireId generated by hbm2java
 */
public class SalaireId  implements java.io.Serializable {


     private String codeprepose;
     private String mois;

    public SalaireId() {
    }

    public SalaireId(String codeprepose, String mois) {
       this.codeprepose = codeprepose;
       this.mois = mois;
    }
   
    public String getCodeprepose() {
        return this.codeprepose;
    }
    
    public void setCodeprepose(String codeprepose) {
        this.codeprepose = codeprepose;
    }
    public String getMois() {
        return this.mois;
    }
    
    public void setMois(String mois) {
        this.mois = mois;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SalaireId) ) return false;
		 SalaireId castOther = ( SalaireId ) other; 
         
		 return ( (this.getCodeprepose()==castOther.getCodeprepose()) || ( this.getCodeprepose()!=null && castOther.getCodeprepose()!=null && this.getCodeprepose().equals(castOther.getCodeprepose()) ) )
 && ( (this.getMois()==castOther.getMois()) || ( this.getMois()!=null && castOther.getMois()!=null && this.getMois().equals(castOther.getMois()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeprepose() == null ? 0 : this.getCodeprepose().hashCode() );
         result = 37 * result + ( getMois() == null ? 0 : this.getMois().hashCode() );
         return result;
   }   


}


