package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Salaire generated by hbm2java
 */
public class Salaire  implements java.io.Serializable {


     private SalaireId id;
     private Employe employe;
     private BigDecimal montant;

    public Salaire() {
    }

    public Salaire(SalaireId id, Employe employe, BigDecimal montant) {
       this.id = id;
       this.employe = employe;
       this.montant = montant;
    }
   
    public SalaireId getId() {
        return this.id;
    }
    
    public void setId(SalaireId id) {
        this.id = id;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public BigDecimal getMontant() {
        return this.montant;
    }
    
    public void setMontant(BigDecimal montant) {
        this.montant = montant;
    }




}


