package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Surveillant generated by hbm2java
 */
public class Surveillant  implements java.io.Serializable {


     private String code;
     private Employe employe;
     private String taux;
     private String grade;
     private Set choixes = new HashSet(0);

    public Surveillant() {
    }

	
    public Surveillant(Employe employe, String taux, String grade) {
        this.employe = employe;
        this.taux = taux;
        this.grade = grade;
    }
    public Surveillant(Employe employe, String taux, String grade, Set choixes) {
       this.employe = employe;
       this.taux = taux;
       this.grade = grade;
       this.choixes = choixes;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public String getTaux() {
        return this.taux;
    }
    
    public void setTaux(String taux) {
        this.taux = taux;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public Set getChoixes() {
        return this.choixes;
    }
    
    public void setChoixes(Set choixes) {
        this.choixes = choixes;
    }




}


