package zoo.entity;
// Generated Apr 23, 2015 11:42:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone  implements java.io.Serializable {


     private String nom;
     private String fonction;
     private Set choixes = new HashSet(0);
     private Set lotissements = new HashSet(0);
     private Set chefdezones = new HashSet(0);
     private Set surveillances = new HashSet(0);

    public Zone() {
    }

	
    public Zone(String nom, String fonction) {
        this.nom = nom;
        this.fonction = fonction;
    }
    public Zone(String nom, String fonction, Set choixes, Set lotissements, Set chefdezones, Set surveillances) {
       this.nom = nom;
       this.fonction = fonction;
       this.choixes = choixes;
       this.lotissements = lotissements;
       this.chefdezones = chefdezones;
       this.surveillances = surveillances;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public Set getChoixes() {
        return this.choixes;
    }
    
    public void setChoixes(Set choixes) {
        this.choixes = choixes;
    }
    public Set getLotissements() {
        return this.lotissements;
    }
    
    public void setLotissements(Set lotissements) {
        this.lotissements = lotissements;
    }
    public Set getChefdezones() {
        return this.chefdezones;
    }
    
    public void setChefdezones(Set chefdezones) {
        this.chefdezones = chefdezones;
    }
    public Set getSurveillances() {
        return this.surveillances;
    }
    
    public void setSurveillances(Set surveillances) {
        this.surveillances = surveillances;
    }




}


